// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "f8deba0e-49cd-4608-9384-6765c4c38285";


const char DEVICE_KEY[]        = "!OtUCylSRMw?ti3N7L6G5vtsG";

// 2) Wi‑Fi bilgileri
const char SSID[] = "RobotistanTeknoPark";
const char PASS[] = "bmc34RbT124";   
void onHumChange(){
  
}
void onBoardTempChange(){

}
void onPirChange(){
  
}

float BoardTemp;
float Hum;
float ldr;
bool pir;
void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
   ArduinoCloud.addProperty(BoardTemp, READWRITE, ON_CHANGE, onBoardTempChange);
  ArduinoCloud.addProperty(Hum, READWRITE, ON_CHANGE, onHumChange);
  ArduinoCloud.addProperty(ldr, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pir, READWRITE, ON_CHANGE, onPirChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
